OPTION_MENU_STYLE = {
    "container": {"background-color": "#123", "border-radius": "0px"},
    "icon": {"color": "white", "font-size": "15px"},
    "nav-link": {
        "color": "white",
        "font-size": "15px",
        "text-align": "left",
        "margin": "0px",
        "--hover-color": "#ffffff30",
    },
    # "nav-link-selected": {
    #     "background-color": "#02ab21b4",
    # },
    "menu-title": {
        "font-size": "16px",
        "color": "#dd13dd",
        "bi-emoji-smile": {"color": "yellow"},
        "font-weight": "bolder",
        "display": "flex",
        "align-items": "center!important",
    },
    "hr": {
        "display": "none",
    },
}
MENUS_BY_LANGUAGES = {
    "en": [
        "Analyses",
        "Results",
        "Infos",
        "About",
        "Logout",
    ],
    "fr": [
        "Analyses",
        "Résultats",
        "Informations",
        "Á propos",
        "Déconnexion",
    ],
    "es": [
        "Análisis",
        "Resultados",
        "Noticia",
        "Acerca de",
        "Cerrar sesión",
    ],
    "de": [
        "Analysen",
        "Ergebnisse",
        "Infos",
        "über mich",
        "Ausloggen",
    ],
}

MENU_ICONS = [
    "lungs-fill",
    "clipboard-data-fill",
    "book-fill",
    "trophy-fill",
    "bi-door-closed-fill",
]
# build list from MENUS_BY_LANGUAGES
MENUS = {
    lang: {MENUS_BY_LANGUAGES[lang][i]: icon for i, icon in enumerate(MENU_ICONS)}
    for _, lang in enumerate(MENUS_BY_LANGUAGES.keys())
}

LANGUAGES = list(MENUS_BY_LANGUAGES.keys())

DICTIONNARY = {
    # OK
    "es": {
        "Cerrar sesión": {"Logout": "Cerrar sesión"},
        "Acerca de": {
            "This application had been build by": "Esta aplicación fue creada por",
            "Passionate about data science and machine learning": "Apasionado por la ciencia de datos y el aprendizaje automático",
            "About Me": "Sobre mí",
        },
        "Borrar": {
            "Drop my data": "Eliminar mis datos",
            "an error occured, please try again": "Se ha producido un error, inténtelo de nuevo",
            "Are you sure you want to delete your data ?": "¿Estás seguro de que quieres eliminar tus datos?",
            "this action is not reversible": "Esta acción es irreversible",
            "Please make your choice.": "Por favor, haga su elección.",
            "Yes": "Sí",
            "No": "No",
            "Confirm": "Confirmar",
            "Delete Data": "Eliminación de datos",
        },
        "Noticia": {
            # title page
            "French Sentiments Analysis of the reviews": "Análisis de sentimiento de las reseñas francesas",
            # explain about app
            "This application allow you to make the analyse for the reviews dataset. To achieve your analyse, you need to follow the current steps :": "Esta aplicación le permite analizar las revisiones de sus conjuntos de datos. Para completar su análisis, debe seguir estos pasos:",
            # firts step
            "Upload dataset": "Importar el conjunto de datos",
            "In this step, you must import the dataset of reviews.<br>**Remember that** : the name of your reviews column must be name's **text** in **lowercase**, otherwise you will receive an error during process of analyses.": "En este paso, debe importar el conjunto de datos de revisión.<br> **Recuerda**: El nombre de tu columna de revisión debe estar **text** en **minúsculas**, de lo contrario recibirás un error durante el proceso de escaneo.",
            # second step
            "Clean dataset": "Limpieza del conjunto de datos",
            "<br>In this step, you will clean the dataset of reviews to optimize the analyses of reviews.<br>**Note** : You can set the numbers of workers depend of your preference.<br>The times of this step depends of the size of your dataset and the number of workers fixed for the cleaning": "En este paso, limpiará todo el conjunto de datos de revisión para optimizar el análisis de revisión.<br>**Nota**: Puede establecer el número de trabajadores según sus preferencias. El tiempo de este paso depende del tamaño de los datasets y del número de trabajadores que establecerá para la limpieza",
            # third step
            "Dataset analyses": "Análisis de conjuntos de datos",
            "<br>In this step,application will make the analyses of all cleaned dataset and produce results that you can interprete and make decisions. You can also set the number of workers for analyse<br>**Note** : The times of this step depends of the size of your dataset and the number of workers fixed for the analyse": "En este paso, la aplicación realizará los análisis de todos los conjuntos de datos limpiados y producirá resultados que puede interpretar y tomar decisiones. También puede establecer el número de trabajadores para el análisis.<br>**Nota**: El tiempo para este paso depende del tamaño de sus conjuntos de datos y la cantidad de trabajadores que establecerá para el análisis",
            "Results of Analyses": "Resultados del análisis",
            # fourth step
            "<br>In this steps, application will be show some results for analyses.<br>**Note** : To show more results, you can go to the **Results** section": "En este paso, la aplicación mostrará algunos resultados del escaneo.<br>**Nota**: Para ver más resultados, puede ir a la sección **Resultados**",
            # tip
            "**Tip** : Application will give you instructions to achieve the goal of analyses.<br>You can use the left sidebar to discover application sections. You can also download all result of analyse if need.": "**Consejo**: La aplicación le dará instrucciones sobre cómo lograr el objetivo de los escaneos. Puede usar la barra lateral izquierda para descubrir las secciones de la aplicación. También puede descargar todos los resultados del análisis si es necesario.",
            # RGPD
            "**RGPD** : You can delete your data at any time in the <b>Delete</b> section of the sidebar if you need.<br>If you have any suggestions, please share it with me on": "RGPD: Puedes eliminar tus datos en cualquier momento en la sección Eliminar de la barra lateral si lo necesitas.<br> Si tiene alguna sugerencia, no dude en compartirla conmigo en",
            "to improve user experience, and application": "para mejorar la experiencia del usuario y la aplicación",
            "Thank you": "Gracias",
        },
        "Análisis": {
            # errors exception
            "CSV file must be encoded in UTF8. Please change the encoding of your csv to UTF8, you can just open your csv file and save it with UTF8 format and try again": "El archivo CSV debe estar codificado en UTF8. Cambie la codificación de su csv a UTF8, simplemente puede abrir su archivo csv y guardarlo en formato UTF8 y volver a intentarlo",
            "Dataframe must be contains 'text' column with all text reviews, please choose another valid file": "Todo el conjunto de datos debe contener una columna de 'text' con todos los avisos de texto, elija otro archivo válido",
            # Analyses
            "French Sentiments Analysis": "Análisis del sentimiento francés",
            "Upload reviews csv file": "Descargar el archivo csv de reseñas",
            "Load users reviews csv file which must contains the 'text' column for users reviews and UTF-8 encoding for dataset": "Cargue el archivo csv de reseñas de usuarios que debe contener la columna 'text' para las reseñas de usuarios y la codificación UTF-8 para el conjunto de datos",
            "Reviews loaded successfully": "Las reseñas se han cargado correctamente",
            "Reviews": "Opiniones",
            "Cleaning up reviews": "Limpieza de reseñas",
            "Set the number of workers": "Establecer el número de trabajadores",
            "Clean Up": "Limpio",
            "set number of workers to use for clean up reviews": "Definir el número de trabajadores que se utilizarán para la limpieza",
            "Clean up reviews process is running. if you want to stop it, click on refresh button on the sidebar": "El proceso de limpieza de revisiones está en curso. Si desea detenerlo, haga clic en el botón Actualizar en la barra lateral.",
            "Cleaning up reviews performed successfully": "Limpieza de revisiones realizadas correctamente",
            "Workers in progress...": "Trabajadores en progreso...",
            "Total workers": "Total de trabajadores",
            "Completed": "Terminado",
            "In progress...": "En curso...",
            "Worker": "Trabajador",
            "Cleaned": "Limpiarse",
            "set number of workers to perform analyse of reviews": "Establecer el número de trabajadores para realizar el análisis",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Seleccione un modelo (AUC: Rendimiento general, Precisión: Porcentaje de un verdadero positivo)",
            "Select model to perform analyse of reviews": "Seleccione una plantilla para realizar un análisis de revisión",
            "Model": "Modelo",
            "Analyze": "Analizar",
            "Analyze performed successfully": "Análisis realizado con éxito",
            "Analyze results": "Resultados del análisis",
            "Select diagram": "Selecciona un gráfico",
            "Select a diagram to show analyze results": "Seleccione un gráfico para ver los resultados del análisis",
            "Analyze Results of Sentiments": "Resultados del análisis de sentimiento",
            "Total reviews": "Opiniones totales",
            "Polarity of reviews": "Polaridad de las reseñas",
            "Polarity count": "Frecuencia de polaridad",
            "polarity": "polaridad",
            "Negative": "Negativo",
            "Positive": "Positivo",
            "Summary of Diagram": "Resumen del diagrama",
            "an error occured, please try again": "Se ha producido un error, inténtelo de nuevo",
            # dialog
            "Are you sure you want to terminate this action ?<br>Rember that all data on the current page will be lost.<br>": "¿Estás seguro de que quieres poner fin a esta acción?<br>Recuerde que se perderán todos los datos de la página actual.<br>",
            "Yes": "Sí",
            "No": "No",
            "Please confirm your choice.": "Por favor, confirme su elección.",
        },
        "Resultados": {
            # display results
            "loading":"cargando",
            "MORE RESULTS":"RESULTADOS ADICIONALES",
            "polarity": "Polaridad",
            "Negative": "Negativo",
            "Positive": "Positivo",
            "Analyze Results of Sentiments": "Resultados del análisis de sentimiento",
            "Polarity count": "Frecuencia de polaridad",
            "Analyze Results of Sentiments": "Resultados del análisis de sentimiento",
            "Total reviews": "Opiniones totales",
            "Polarity of reviews": "Polaridad de las reseñas",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Seleccione un modelo (AUC: Rendimiento general, Precisión: Porcentaje de un verdadero positivo)",
            "Select model to show analyze results of reviews": "Seleccione una plantilla para ver los resultados del análisis de revisión",
            "Select diagram": "Selecciona un gráfico",
            "Select a diagram to show analyze results": "Seleccione un gráfico para ver los resultados del análisis",
            "Model": "Modelo",
            "Last Reviews": "Últimas reseñas",
            "Analyze results": "Resultados del análisis",
            "Pages": "Páginas",
            "Positives words": "Palabras positivas",
            "Negatives words": "Palabras negativas",
            "Positives words cloud": "Nubes de palabras positivas",
            "Negatives words cloud": "Nubes de palabras negativas",
            "Positives words frequencies": "Frecuencias de palabras positivas",
            "Negatives words frequencies": "Frecuencias de palabras negativas",
            "words": "palabras",
            "polarity": "polaridad",
            "count": "Frecuencia",
            "Analyze Results of words polarity": "Resultados del análisis de polaridad de palabras",
            "Total words": "Palabras totales",
            "Download complete summary analyze": "Descargue el resumen del análisis",
            # files names
            "summary_analyse.zip": "Análisis_resumido.zip",
            "negatives_words_frequencies.csv": "Frecuencias_de_palabras_negativas.csv",
            "words_analysis_results_table_metrics.csv": "Tabla_de_métricas_Word_Analytics.csv",
            "positives_words_frequencies.csv": "Frecuencias_de_palabras_positivas.csv",
            "words_sentiments_analysis_results.png": "Resultados_Análisis_de_sentimiento_de palabras.png",
            "sentiments_analysis_results.png": "Resultados_del_análisis_de_sentimiento.png",
            "sentiments_analysis_results_table_metrics.csv": "Tabla_de_análisis_de_sentimiento_de métricas.csv",
            "Polarities": "Polaridades",
            "Words Polarities Results": "Resultados de polaridad de palabras",
        },
    },
    # OK
    "fr": {
        "Déconnexion": {"Logout": "Se déconnecter"},
        "Á propos": {
            "This application had been build by": "Cette application a été créée par",
            "Passionate about data science and machine learning": "passionné par la science des données et l'apprentissage automatique",
            "About Me": "Á propos de moi",
        },
        "Supprimer": {
            "Drop my data": "Supprimer mes données",
            "an error occured, please try again": "une erreur est survenue,essayer encore s'il vous plait",
            "Are you sure you want to delete your data ?": "Êtes vous sure de vouloir supprimer vos données ?",
            "this action is not reversible": "Cette action est irréversible",
            "Please make your choice.": "S'il vous plait faite votre choix.",
            "Yes": "Oui",
            "No": "Non",
            "Confirm": "Confirmer",
            "Delete Data": "Suppression Des Données",
        },
        "Informations": {
            # title page
            "French Sentiments Analysis of the reviews": "Analyses des sentiments des avis français",
            # explain app
            "This application allow you to make the analyse for the reviews dataset. To achieve your analyse, you need to follow the current steps :": "Cette application vous permet d'analyser les avis de vos jeux de données. Pour accomplir votre analyse, vous devez suivre les etapes suivantes :",
            # first step
            "Upload dataset": "Importer votre jeux de données",
            "In this step, you must import the dataset of reviews.<br>**Remember that** : the name of your reviews column must be name's **text** in **lowercase**, otherwise you will receive an error during process of analyses.": "Dans cette étape, vous devez importer le jeu de données d'avis.<br>**N'oubliez pas que** : le nom de votre colonne d'avis doit être **texte** en **minuscule**, sinon vous recevrez une erreur lors du processus d'analyse.",
            # second step
            "Clean dataset": "Nettoyage du jeux de données",
            "<br>In this step, you will clean the dataset of reviews to optimize the analyses of reviews.<br>**Note** : You can set the numbers of workers depend of your preference.<br>The times of this step depends of the size of your dataset and the number of workers fixed for the cleaning": "Dans cette étape, vous allez nettoyer l'ensemble du jeux de données d'avis pour optimiser l'analyses des avis.<br>**Note** : Vous pouvez définir le nombre de travailleurs en fonction de vos préférences. le temps de Cette étape depend de la taille de vos jeux de données et du nombres de travailleurs que vous allez fixer pour le nettoyage",
            # third step
            "Dataset analyses": "Analyse du jeux de données",
            "<br>In this step,application will make the analyses of all cleaned dataset and produce results that you can interprete and make decisions. You can also set the number of workers for analyse<br>**Note** : The times of this step depends of the size of your dataset and the number of workers fixed for the analyse": "Dans cette étape, l'application effectuera les analyses de tous les ensembles de données nettoyées et produira des résultats que vous pouvez interpréter et prendre des décisions. Vous pouvez également définir le nombre de travailleurs pour l'analyse.<br>**Remarque** : le temps de Cette étape depend de la taille de vos jeux de données et du nombre de travailleurs que vous allez fixer pour l'analyse",
            # fourth step
            "Results of Analyses": "Résultats de l'analyse",
            "<br>In this steps, application will be show some results for analyses.<br>**Note** : To show more results, you can go to the **Results** section": "Dans cette étape, l'application affichera quelques résultats d'analyses.<br>**Remarque** : Pour afficher plus de résultats, vous pouvez vous rendre dans la section **Résultats**",
            # tip
            "**Tip** : Application will give you instructions to achieve the goal of analyses.<br>You can use the left sidebar to discover application sections. You can also download all result of analyse if need.": "**Astuce** : L'application vous donnera des instructions pour atteindre l'objectif des analyses. Vous pouvez utiliser la barre latérale gauche pour découvrir les section de l'application. Vous pouvez également télécharger tous les résultats de l'analyse si nécessaire.",
            # RGPD
            "**RGPD** : You can delete your data at any time in the <b>Delete</b> section of the sidebar if you need.<br>If you have any suggestions, please share it with me on": "**RGPD** : Vous pouvez supprimer vos données à tous moment dans la section **Supprimer** de la barre latérale si vous en avez besoin.<br>Si vous avez des suggestions, n'hésitez pas à les partager avec moi sur",
            "to improve user experience, and application": "pour améliorer l'expérience de l'utilisateur et l'application",
            "Thank you": "Je vous remerci",
        },
        "Analyses": {
            # error exceptions
            "CSV file must be encoded in UTF8. Please change the encoding of your csv to UTF8, you can just open your csv file and save it with UTF8 format and try again": "Le fichier CSV doit être encodé en UTF8. Veuillez changer l'encodage de votre csv en UTF8, vous pouvez simplement ouvrir votre fichier csv et l'enregistrer au format UTF8 et réessayer",
            "Dataframe must be contains 'text' column with all text reviews, please choose another valid file": "L'ensemble du jeux de données doit contenir une colonne 'text' avec tous les avis de texte, veuillez choisir un autre fichier valide s'il vous plait",
            # Analyses
            "French Sentiments Analysis": "Analyses Des Sentiments Français",
            "Upload reviews csv file": "Télécharger le fichier csv des avis",
            "Load users reviews csv file which must contains the 'text' column for users reviews and UTF-8 encoding for dataset": "Chargez le fichier csv des avis des utilisateurs qui doit contenir la colonne 'text' pour les avis des utilisateurs et l'encodage UTF-8 pour le jeux de données",
            "Reviews loaded successfully": "Les avis ont été chargés avec succès",
            "Reviews": "Avis",
            "Cleaning up reviews": "Nettoyage des avis",
            "Set the number of workers": "Définissez le nombre de travailleurs",
            "Clean Up": "Nettoyer",
            "set number of workers to use for clean up reviews": "définir le nombre de travailleurs à utiliser pour le nettoyage",
            "Clean up reviews process is running. if you want to stop it, click on refresh button on the sidebar": "Le processus de nettoyage des avis est en cours. Si vous souhaitez l'arrêter, cliquez sur le bouton Actualiser dans la barre latérale.",
            "Cleaning up reviews performed successfully": "Nettoyage des avis effectués avec succès",
            "Workers in progress...": "Ouvriers en cours...",
            "Total workers": "Total des Ouvriers",
            "Completed": "Terminé",
            "In progress...": "En cours...",
            "Worker": "Ouvrier",
            "Cleaned": "Nettoyés",
            "set number of workers to perform analyse of reviews": "Définissez le nombre de travailleurs pour effectuer l'analyse",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Selectionner un modèle(AUC : Performance globale, Accuracy : pourcentage d'un vrai positif)",
            "Select model to perform analyse of reviews": "Selectionner un modèle pour effectuer l'analyse des avis",
            "Model": "Modèle",
            "Analyze": "Analyser",
            "Analyze performed successfully": "Analyse effectuée avec succès",
            "Analyze results": "Résultats de l'analyse",
            "Select diagram": "Selectionner un diagramme",
            "Select a diagram to show analyze results": "Sélectionnez un diagramme pour afficher les résultats de l'analyse",
            "Analyze Results of Sentiments": "Résultats de l'analyse des sentiments",
            "Total reviews": "avis au total",
            "Polarity of reviews": "Polarité des avis",
            "Polarity count": "Fréquence de polarités",
            "polarity": "polarité",
            "Negative": "Négatif",
            "Positive": "Positif",
            "Summary of Diagram": "Résumé du diagramme",
            "an error occured, please try again": "une erreur est survenue,essayer encore s'il vous plait",
            # dialog
            "Are you sure you want to terminate this action ?<br>Rember that all data on the current page will be lost.<br>": "Êtes-vous sûr de vouloir mettre fin à cette action?<br> sachez que toutes les données de la page actuelle seront perdues.",
            "Yes": "Oui",
            "No": "Non",
            "Please confirm your choice.": "S'il vous plait confirmez votre choix",
        },
        "Résultats": {
            # display results
            "loading":"chargement",
            "MORE RESULTS":"plus de résultats",
            "polarity": "polarité",
            "Negative": "Négatif",
            "Positive": "Positif",
            "Analyze Results of Sentiments": "Résultats de l'analyse des sentiments",
            "Polarity count": "Fréquence de polarités",
            "Analyze Results of Sentiments": "Résultats de l'analyse des sentiments",
            "Total reviews": "avis au total",
            "Polarity of reviews": "Polarité des avis",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Selectionner un modèle(AUC : Performance globale, Accuracy : pourcentage d'un vrai positif)",
            "Select model to show analyze results of reviews": "Selectionner un modèle pour voir les résultats d'analyses des avis",
            "Select diagram": "Selectionner un diagramme",
            "Select a diagram to show analyze results": "Sélectionnez un diagramme pour afficher les résultats de l'analyse",
            "Model": "Modèle",
            "Last Reviews": "Derniers avis",
            "Analyze results": "Résultats de l'analyse",
            "Pages": "Pages",
            "Positives words": "Mots positifs",
            "Negatives words": "Mots Negatives",
            "Positives words cloud": "Nuages de mots positifs",
            "Negatives words cloud": "Nuages de mots négatifs",
            "Positives words frequencies": "Fréquences des mots positifs",
            "Negatives words frequencies": "Fréquences des mots négatifs",
            "words": "mots",
            "polarity": "polarité",
            "count": "frequence",
            "Analyze Results of words polarity": "Résultats de l'analyse de la polarité des mots",
            "Total words": "mots au total",
            "Download complete summary analyze": "Téléchargez le résumé de l'analyse",
            # files names
            "summary_analyse.zip": "Résumé_analyse.zip",
            "negatives_words_frequencies.csv": "fréquences_des_mots_négatifs.csv",
            "words_analysis_results_table_metrics.csv": "table_des_métriques_analyses_des_mots.csv",
            "positives_words_frequencies.csv": "fréquences_des_mots_positifs.csv",
            "words_sentiments_analysis_results.png": "résultats_analyse_des_sentiments_des_mots.png",
            "sentiments_analysis_results.png": "résultats_analyse_des_sentiments.png",
            "sentiments_analysis_results_table_metrics.csv": "table_métriques_analyse_des_sentiments.csv",
            "Polarities": "Polarités",
            "Words Polarities Results": "Résultats de la polarité des mots",
        },
    },
    # OK
    "de": {
        "Ausloggen": {"Logout": "Ausloggen"},
        "über mich": {
            "This application had been build by": "Diese Anwendung wurde erstellt von",
            "Passionate about data science and machine learning": "Leidenschaft für Data Science und maschinelles Lernen",
            "About Me": "Über mich",
        },
        "löschen": {
            "Drop my data": "Meine Daten löschen",
            "an error occured, please try again": "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
            "Are you sure you want to delete your data ?": "Möchten Sie Ihre Daten wirklich löschen?",
            "this action is not reversible": "Diese Aktion ist irreversibel",
            "Please make your choice.": "Bitte treffen Sie Ihre Auswahl.",
            "Yes": "Ja",
            "No": "Nein danke",
            "Confirm": "Bestätigen",
            "Delete Data": "Datenlöschung",
        },
        "Infos": {
            # title page
            "French Sentiments Analysis of the reviews": "Sentimentanalyse französischer Rezensionen",
            # explain app
            "This application allow you to make the analyse for the reviews dataset. To achieve your analyse, you need to follow the current steps :": "Mit dieser Anwendung können Sie die Bewertungen Ihrer Datensätze analysieren. Um Ihre Analyse abzuschließen, müssen Sie die folgenden Schritte ausführen : ",
            # first step
            "Upload dataset": "Importieren Sie Ihren Datensatz",
            "In this step, you must import the dataset of reviews.<br>**Remember that** : the name of your reviews column must be name's **text** in **lowercase**, otherwise you will receive an error during process of analyses.": "In diesem Schritt müssen Sie den Bewertungsdatensatz importieren.<br>**Denken Sie daran**: Der Name Ihrer Bewertungsspalte muss **text** in **Kleinbuchstaben** sein, andernfalls erhalten Sie während des Analysevorgangs eine Fehlermeldung.",
            # second step
            "Clean dataset": "Bereinigen des Datensatzes",
            "<br>In this step, you will clean the dataset of reviews to optimize the analyses of reviews.<br>**Note** : You can set the numbers of workers depend of your preference.<br>The times of this step depends of the size of your dataset and the number of workers fixed for the cleaning": "In diesem Schritt bereinigen Sie den gesamten Bewertungsdatensatz, um die Bewertungsanalyse zu optimieren.<br>**Hinweis**: Sie können die Anzahl der Mitarbeiter nach Ihren Wünschen festlegen. Die Dauer dieses Schritts hängt von der Größe Ihrer Datensätze und der Anzahl der Mitarbeiter ab, die Sie für die Bereinigung festlegen.",
            # third step
            "Dataset analyses": "Datensatzanalyse",
            "<br>In this step,application will make the analyses of all cleaned dataset and produce results that you can interprete and make decisions. You can also set the number of workers for analyse<br>**Note** : The times of this step depends of the size of your dataset and the number of workers fixed for the analyse": "In diesem Schritt analysiert die Anwendung alle bereinigten Datensätze und liefert Ergebnisse, die Sie interpretieren und auf deren Grundlage Sie Entscheidungen treffen können. Sie können auch die Anzahl der Mitarbeiter für die Analyse festlegen.<br>**Hinweis**: Die Dauer dieses Schritts hängt von der Größe Ihrer Datensätze und der Anzahl der Mitarbeiter ab, die Sie für die Analyse festlegen.",
            # fourth step
            "Results of Analyses": "Analyseergebnisse",
            "<br>In this steps, application will be show some results for analyses.<br>**Note** : To show more results, you can go to the **Results** section": "In diesem Schritt zeigt die Anwendung einige Analyseergebnisse an.<br>**Hinweis**: Um weitere Ergebnisse anzuzeigen, können Sie zum Abschnitt **Ergebnisse** gehen.",
            # tip
            "**Tip** : Application will give you instructions to achieve the goal of analyses.<br>You can use the left sidebar to discover application sections. You can also download all result of analyse if need.": "**Tipp**: Die App gibt Ihnen Anweisungen zum Durchführen der Scans. Über die linke Seitenleiste können Sie die einzelnen Bereiche der App erkunden. Bei Bedarf können Sie auch alle Scan-Ergebnisse herunterladen.",
            # RGPD
            "**RGPD** : You can delete your data at any time in the <b>Delete</b> section of the sidebar if you need.<br>If you have any suggestions, please share it with me on": "**RGPD(DSGVO)**: Sie können Ihre Daten jederzeit im Abschnitt **Löschen** der Seitenleiste löschen, wenn Sie dies benötigen.<br>Wenn Sie Vorschläge haben, teilen Sie sie mir bitte mit auf",
            "to improve user experience, and application": "um die Benutzererfahrung und die Anwendung zu verbessern",
            "Thank you": "Ich danke Ihnen",
        },
        "Analysen": {
            # error exceptions
            "CSV file must be encoded in UTF8. Please change the encoding of your csv to UTF8, you can just open your csv file and save it with UTF8 format and try again": "Die CSV-Datei muss in UTF8 kodiert sein. Bitte ändern Sie die Kodierung Ihrer CSV-Datei in UTF8. Sie können Ihre CSV-Datei einfach öffnen, als UTF8 speichern und es erneut versuchen.",
            "Dataframe must be contains 'text' column with all text reviews, please choose another valid file": "Der gesamte Datensatz muss eine Spalte „text“ mit allen Textbewertungen enthalten. Bitte wählen Sie eine andere gültige Datei.",
            # Analyses
            "French Sentiments Analysis": "Analyse der französischen Stimmung",
            "Upload reviews csv file": "Laden Sie die CSV-Datei mit den Bewertungen herunter",
            "Load users reviews csv file which must contains the 'text' column for users reviews and UTF-8 encoding for dataset": "Laden Sie die CSV-Datei mit den Benutzerbewertungen hoch, die die Spalte „text“ für Benutzerbewertungen und die UTF-8-Kodierung für den Datensatz enthalten sollte.",
            "Reviews loaded successfully": "Bewertungen wurden erfolgreich geladen",
            "Reviews": "beachten",
            "Cleaning up reviews": "Bewertungen bereinigen",
            "Set the number of workers": "Legen Sie die Anzahl der Mitarbeiter fest",
            "Clean Up": "reinigen",
            "set number of workers to use for clean up reviews": "Legen Sie die Anzahl der für die Reinigung einzusetzenden Arbeiter fest",
            "Clean up reviews process is running. if you want to stop it, click on refresh button on the sidebar": "Der Überprüfungsprozess läuft. Um ihn zu stoppen, klicken Sie auf die Schaltfläche „Aktualisieren“ in der Seitenleiste.",
            "Cleaning up reviews performed successfully": "Überprüfungsbereinigung erfolgreich abgeschlossen",
            "Workers in progress...": "Arbeiter in Arbeit ...",
            "Total workers": "Gesamtzahl der Arbeitnehmer",
            "Completed": "fertig",
            "In progress...": "Im Gange...",
            "Worker": "Arbeitnehmer",
            "Cleaned": "Gereinigt",
            "set number of workers to perform analyse of reviews": "Legen Sie die Anzahl der Mitarbeiter fest, die die Analyse durchführen sollen",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Wählen Sie ein Modell aus (AUC: Gesamtleistung, Genauigkeit: Prozentsatz eines echten Positivs)",
            "Select model to perform analyse of reviews": "Wählen Sie eine Vorlage aus, um eine Überprüfungsanalyse durchzuführen",
            "Model": "Modell",
            "Analyze": "Analysieren",
            "Analyze performed successfully": "Analyse erfolgreich abgeschlossen",
            "Analyze results": "Analyseergebnisse",
            "Select diagram": "Wählen Sie ein Diagramm aus",
            "Select a diagram to show analyze results": "Wählen Sie ein Diagramm aus, um die Analyseergebnisse anzuzeigen",
            "Analyze Results of Sentiments": "Ergebnisse der Stimmungsanalyse",
            "Total reviews": "Gesamtbewertungen",
            "Polarity of reviews": "Polarität der Meinungen",
            "Polarity count": "Polaritätsfrequenz",
            "polarity": "Polarität",
            "Negative": "Negativ",
            "Positive": "Positiv",
            "Summary of Diagram": "Diagrammzusammenfassung",
            "an error occured, please try again": "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
            # dialog
            "Are you sure you want to terminate this action ?<br>Rember that all data on the current page will be lost.<br>": "Möchten Sie diese Aktion wirklich beenden?<br> Bitte beachten Sie, dass dabei alle Daten auf der aktuellen Seite verloren gehen.",
            "Yes": "Ja",
            "No": "Nein danke",
            "Please confirm your choice.": "Bitte bestätigen Sie Ihre Auswahl",
        },
        "Ergebnisse": {
            # display results
            "loading":"Laden",
            "MORE RESULTS":"WEITERE ERGEBNISSE",
            "polarity": "Polarität",
            "Negative": "Negativ",
            "Positive": "Positiv",
            "Analyze Results of Sentiments": "Ergebnisse der Stimmungsanalyse",
            "Polarity count": "Polaritätsfrequenz",
            "Total reviews": "Gesamtbewertungen",
            "Polarity of reviews": "Polarität der Meinungen",
            "Select a model(AUC : Overall Performance, Accuracy : Percent Of True Positif)": "Wählen Sie ein Modell aus (AUC: Gesamtleistung, Genauigkeit: Prozentsatz eines echten Positivs)",
            "Select model to show analyze results of reviews": "Wählen Sie ein Modell aus, um die Ergebnisse der Überprüfungsanalyse anzuzeigen",
            "Select diagram": "Wählen Sie ein Diagramm aus",
            "Select a diagram to show analyze results": "Wählen Sie ein Diagramm aus, um die Analyseergebnisse anzuzeigen",
            "Model": "Modèle",
            "Last Reviews": "Neueste Bewertungen",
            "Analyze results": "Analyseergebnisse",
            "Pages": "Wählen Sie die Seitenzahl",
            "Positives words": "Positive Worte",
            "Negatives words": "Negative Wörter",
            "Positives words cloud": "Positive Wortwolken",
            "Negatives words cloud": "Negative Wortwolken",
            "Positives words frequencies": "Häufigkeit positiver Wörter",
            "Negatives words frequencies": "Häufigkeit negativer Wörter",
            "words": "Wörter",
            "polarity": "Polarität",
            "count": "Frequenz",
            "Analyze Results of words polarity": "Ergebnisse der Wortpolaritätsanalyse",
            "Total words": "Wörter insgesamt",
            "Download complete summary analyze": "Laden Sie die Analysezusammenfassung herunter",
            # files names
            "summary_analyse.zip": "Zusammenfassung_Analyse.zip",
            "negatives_words_frequencies.csv": "Häufigkeit_negativer_Wörter.csv",
            "words_analysis_results_table_metrics.csv": "Tabelle_der_Metriken_Wortanalyse.csv",
            "positives_words_frequencies.csv": "Häufigkeit_positiver_Wörter.csv",
            "words_sentiments_analysis_results.png": "Ergebnisanalyse_der_Wortstimmungen.png",
            "Ergebnisse_der_Stimmungsanalyse.png": "Ergebnisse_Stimmungsanalyse.png",
            "sentiments_analysis_results_table_metrics.csv": "Tabellenmetriken_Stimmungsanalyse.csv",
            "Polarities": "Polaritäten",
            "Words Polarities Results": "Ergebnisse der Wortpolarität",
        },
    },
}
